FROM golang:1.24 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
ENV GOPROXY=https://goproxy.io,direct
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o privat-unmei-cron cmd/cron/main.go

FROM alpine:latest AS release-stage

WORKDIR /

COPY --from=build-stage /usr/share/zoneinfo /usr/share/zoneinfo

COPY --from=build-stage /app/privat-unmei-cron privat-unmei-cron
COPY --from=build-stage /app/.env .env

ENTRYPOINT [ "/bin/sh", "-c", "/privat-unmei-cron"]
