FROM alpine:latest

WORKDIR /

COPY --from=golang:1.24 /usr/share/zoneinfo /usr/share/zoneinfo

COPY privat-unmei-migrate /privat-unmei-migrate
COPY .env /.env
COPY db/migrations ./db/migrations 
COPY db/seeds ./db/seeds 

ENTRYPOINT [ "/bin/sh", "-c", "/privat-unmei-migrate"]