FROM alpine:latest

WORKDIR /

COPY --from=golang:1.24 /usr/share/zoneinfo /usr/share/zoneinfo

COPY privat-unmei-cron /privat-unmei-cron
COPY .env /.env

ENTRYPOINT [ "/bin/sh", "-c", "/privat-unmei-cron"]