FROM alpine:latest

WORKDIR /

COPY --from=golang:1.24 /usr/share/zoneinfo /usr/share/zoneinfo
COPY privat-unmei-backend /privat-unmei-backend
COPY .env /.env

EXPOSE 8080

ENTRYPOINT [ "/bin/sh", "-c", "/privat-unmei-backend"]