CREATE TABLE additional_costs (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE,
    amount NUMERIC NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);