CREATE TABLE students (
    id UUID PRIMARY KEY NOT NULL REFERENCES users(id),
    verify_token VARCHAR UNIQUE,
    reset_token VARCHAR UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);